// js/core/seed_data.js
export const CATEGORY_MAP = {
    'Antibiotics': { ar: 'مضادات حيوية', icon: 'bx-dna', color: '#3b82f6', prefix: 'A' },
    'NSAID': { ar: 'مسكنات وآلام', icon: 'bx-plus-medical', color: '#ef4444', prefix: 'B' },
    'Anti-Flu': { ar: 'أدوية البرد', icon: 'bx-wind', color: '#06b6d4', prefix: 'C' },
    'Laryng.': { ar: 'أذن وحنجرة', icon: 'bx-microphone-off', color: '#8b5cf6', prefix: 'D' },
    'Local Prep': { ar: 'كريمات ودهانات', icon: 'bx-spray-can', color: '#10b981', prefix: 'E' },
    'GIT Prep': { ar: 'أدوية المعدة', icon: 'bx-dish', color: '#f59e0b', prefix: 'F' },
    'Respiratory': { ar: 'جهاز تنفسي', icon: 'bx-mask', color: '#6366f1', prefix: 'G' },
    'Eye-Ear-Nose': { ar: 'قطرات عيون وأذن', icon: 'bx-bullseye', color: '#ec4899', prefix: 'H' },
    'Injections': { ar: 'حقن', icon: 'bx-injection', color: '#f43f5e', prefix: 'I' },
    'Consumables': { ar: 'مستلزمات طبية', icon: 'bx-package', color: '#64748b', prefix: 'J' }
};

export const SEED_MEDICINES = [
    { "id": "1001", "nameEN": "Hibiotic 1 gm tab", "nameAR": "Hibiotic 1 gm tab", "categoryId": "Antibiotics", "type": "medicine", "imagePath": "assets/products/A01.png" },
    { "id": "1002", "nameEN": "augmentin 1 GM", "nameAR": "augmentin 1 GM", "categoryId": "Antibiotics", "type": "medicine", "imagePath": "assets/products/A02.png" },
    { "id": "1003", "nameEN": "xithrone 500 tab (5 tab)", "nameAR": "xithrone 500 tab (5 tab)", "categoryId": "Antibiotics", "type": "medicine", "imagePath": "assets/products/A03.png" },
    { "id": "1004", "nameEN": "Ciprofar 500", "nameAR": "Ciprofar 500", "categoryId": "Antibiotics", "type": "medicine", "imagePath": "assets/products/A04.png" },
    { "id": "1005", "nameEN": "Flumox 500", "nameAR": "Flumox 500", "categoryId": "Antibiotics", "type": "medicine", "imagePath": "assets/products/A05.png" },
    { "id": "1006", "nameEN": "dalacin c 300", "nameAR": "dalacin c 300", "categoryId": "Antibiotics", "type": "medicine", "imagePath": "assets/products/A06.png" },
    { "id": "1007", "nameEN": "Paracetamol", "nameAR": "Paracetamol", "categoryId": "Antibiotics", "type": "medicine", "imagePath": "assets/products/A07.png" },
    { "id": "1008", "nameEN": "Panadol Advance / dolipran", "nameAR": "Panadol Advance / dolipran", "categoryId": "Antibiotics", "type": "medicine", "imagePath": "assets/products/A08.png" },
    { "id": "1009", "nameEN": "bi-profenid", "nameAR": "bi-profenid", "categoryId": "NSAID", "type": "medicine", "imagePath": "assets/products/B01.png" },
    { "id": "1010", "nameEN": "flotac cap", "nameAR": "flotac cap", "categoryId": "NSAID", "type": "medicine", "imagePath": "assets/products/B02.png" },
    { "id": "1011", "nameEN": "Ketofan 50 mg cap", "nameAR": "Ketofan 50 mg cap", "categoryId": "NSAID", "type": "medicine", "imagePath": "assets/products/B03.png" },
    { "id": "1012", "nameEN": "Cataflam 50mg tab.", "nameAR": "Cataflam 50mg tab.", "categoryId": "NSAID", "type": "medicine", "imagePath": "assets/products/B04.png" },
    { "id": "1013", "nameEN": "Catafast Sachets", "nameAR": "Catafast Sachets", "categoryId": "NSAID", "type": "medicine", "imagePath": "assets/products/B05.png" },
    { "id": "1014", "nameEN": "celebrex 200 mg", "nameAR": "celebrex 200 mg", "categoryId": "NSAID", "type": "medicine", "imagePath": "assets/products/B06.png" },
    { "id": "1015", "nameEN": "Myofen", "nameAR": "Myofen", "categoryId": "NSAID", "type": "medicine", "imagePath": "assets/products/B07.png" },
    { "id": "1016", "nameEN": "Ms.Relaxan Dimra", "nameAR": "Ms.Relaxan Dimra", "categoryId": "NSAID", "type": "medicine", "imagePath": "assets/products/B08.png" },
    { "id": "1017", "nameEN": "multirelax 5 MG", "nameAR": "multirelax 5 MG", "categoryId": "NSAID", "type": "medicine", "imagePath": "assets/products/B09.png" },
    { "id": "1018", "nameEN": "Relaxon cap", "nameAR": "Relaxon cap", "categoryId": "NSAID", "type": "medicine", "imagePath": "assets/products/B10.png" },
    { "id": "1019", "nameEN": "Alphintern", "nameAR": "Alphintern", "categoryId": "NSAID", "type": "medicine", "imagePath": "assets/products/B11.png" },
    { "id": "1020", "nameEN": "Panadol cold & Flu", "nameAR": "Panadol cold & Flu", "categoryId": "Anti-Flu", "type": "medicine", "imagePath": "assets/products/C01.png" },
    { "id": "1021", "nameEN": "DECANSET", "nameAR": "DECANSET", "categoryId": "Anti-Flu", "type": "medicine", "imagePath": "assets/products/C02.png" },
    { "id": "1022", "nameEN": "telefast 180 mg", "nameAR": "telefast 180 mg", "categoryId": "Anti-Flu", "type": "medicine", "imagePath": "assets/products/C03.png" },
    { "id": "1023", "nameEN": "claritin", "nameAR": "claritin", "categoryId": "Anti-Flu", "type": "medicine", "imagePath": "assets/products/C04.png" },
    { "id": "1024", "nameEN": "zyrtec", "nameAR": "zyrtec", "categoryId": "Anti-Flu", "type": "medicine", "imagePath": "assets/products/C05.png" },
    { "id": "1025", "nameEN": "Rhinopro SR", "nameAR": "Rhinopro SR", "categoryId": "Anti-Flu", "type": "medicine", "imagePath": "assets/products/C06.png" },
    { "id": "1026", "nameEN": "SEMSEM Loz", "nameAR": "SEMSEM Loz", "categoryId": "Laryng.", "type": "medicine", "imagePath": "assets/products/D01.png" },
    { "id": "1027", "nameEN": "Larypro", "nameAR": "Larypro", "categoryId": "Laryng.", "type": "medicine", "imagePath": "assets/products/D02.png" },
    { "id": "1028", "nameEN": "Cretard 500mg C", "nameAR": "Cretard 500mg C", "categoryId": "Laryng.", "type": "medicine", "imagePath": "assets/products/D03.png" },
    { "id": "1029", "nameEN": "selgon", "nameAR": "selgon", "categoryId": "Respiratory", "type": "medicine", "imagePath": "assets/products/G01.png" },
    { "id": "1030", "nameEN": "phenadone syrup", "nameAR": "phenadone syrup", "categoryId": "Respiratory", "type": "medicine", "imagePath": "assets/products/G02.png" },
    { "id": "1031", "nameEN": "prozolin", "nameAR": "prozolin", "categoryId": "Eye-Ear-Nose", "type": "medicine", "imagePath": "assets/products/H01.png" },
    { "id": "1032", "nameEN": "voltarine amp", "nameAR": "voltarine amp", "categoryId": "Injections", "type": "emergency", "imagePath": "assets/products/I01.png" },
    { "id": "1033", "nameEN": "dexamethazone amp", "nameAR": "dexamethazone amp", "categoryId": "Injections", "type": "emergency", "imagePath": "assets/products/I02.png" },
    { "id": "1034", "nameEN": "avil amp", "nameAR": "avil amp", "categoryId": "Injections", "type": "emergency", "imagePath": "assets/products/I03.png" },
    { "id": "1035", "nameEN": "heparin", "nameAR": "heparin", "categoryId": "Injections", "type": "emergency", "imagePath": "assets/products/I04.png" },
    { "id": "1036", "nameEN": "clexan 40", "nameAR": "clexan 40", "categoryId": "Injections", "type": "emergency", "imagePath": "assets/products/I05.png" },
    { "id": "1037", "nameEN": "Kapron amp", "nameAR": "Kapron amp", "categoryId": "Injections", "type": "emergency", "imagePath": "assets/products/I06.png" },
    { "id": "1038", "nameEN": "plavix", "nameAR": "plavix", "categoryId": "Injections", "type": "medicine", "imagePath": "assets/products/I07.png" },
    { "id": "1039", "nameEN": "nitoderm patch 5", "nameAR": "nitoderm patch 5", "categoryId": "Injections", "type": "medicine", "imagePath": "assets/products/I08.png" },
    { "id": "1040", "nameEN": "daflon", "nameAR": "daflon", "categoryId": "Injections", "type": "medicine", "imagePath": "assets/products/I09.png" },
    { "id": "1041", "nameEN": "cefatraxone eva 1 gm", "nameAR": "cefatraxone eva 1 gm", "categoryId": "Consumables", "type": "supply", "imagePath": "assets/products/J01.png" },
    { "id": "1042", "nameEN": "N.saline 0.9% 500 ml", "nameAR": "N.saline 0.9% 500 ml", "categoryId": "Consumables", "type": "supply", "imagePath": "assets/products/J02.png" },
    { "id": "1043", "nameEN": "iv cannula g 18", "nameAR": "iv cannula g 18", "categoryId": "Consumables", "type": "supply", "imagePath": "assets/products/J03.png" },
    { "id": "1044", "nameEN": "iv cannula g 20", "nameAR": "iv cannula g 20", "categoryId": "Consumables", "type": "supply", "imagePath": "assets/products/J04.png" }
];
